#!/bin/bash

echo "--- begin project specific setup for SMHI-Waterflow --"

# TODO
# Add project specific setup directives to this file
# It will be called by "container setup-project" (see devcontainer.json postCreateCommand)

add_ha_resource /local/smhi-waterflow-card/dist/smhi-waterflow-card.js

# link lovelace panel for the waterflow-card (sub module repo)
echo "Linking $WORKSPACE_DIR/smhi-waterflow-card/lovelace-panel.yaml to $HA_CONFIG_DIR/panel.yaml"
ln -sf $WORKSPACE_DIR/smhi-waterflow-card/lovelace-panel.yaml $HA_CONFIG_DIR/panel.yaml


pip install pytest pytest-asyncio httpx pydantic pandas

# frontend dependencies
cd /workspaces/smhi-waterflow/smhi-waterflow-card  # Adjust path if needed
npm install

